### ISSUE TITLE
(Chrome) Images don't seem to make it into history

### ISSUE THREAD

**Issue by AsaAyers** [honestbleeps/BetterZoom#17]
It looks like there's capability to add URLs to the history, but I don't think anything is using it. BetterZoom doesn't turn reddit links blue when I hover to view them.

If someone can point me in the right direction I'll see if I can fix this.

**Comment by honestbleeps** [comment]
That's correct, right now BetterZoom isn't adding URLs to history.

It certainly can be! If you're up for contributing code I'd suggest doing
it when the 'load' event fires (where we're already grabbing the size of
the image)...

**Comment by honestbleeps** [comment]
I should add: BabelExt has an abstraction to make this cross-browser,
please use that and not Chrome's native method!
